title: Welcome to the personal page of Tianyi Tian
page-top-title: Tianyi Tian
top-section-bg-text: Be what you wanna be
home-subtitle: Tianyi Tian&ensp;
copyright-text: '&copy; Tianyi Tian 2025. All Rights Reserved.'
